---
kind: pipeline
name: focal_release
type: docker

steps:
  - name: build core image
    image: omerxx/drone-ecr-auth
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
    commands:
      - docker build -t "focalreleaser" -f Dockerfiles/ubuntu-pam-devel.Dockerfile .
    when:
      event:
          - tag
  - name: build
    image: focalreleaser
    pull: never
    commands:
      - cd cmd/focal
      - go build
    when:
      event:
        - tag
  - name: release
    image: focalreleaser
    pull: never
    commands:
      - cd cmd/focal
      - goreleaser --skip-validate --skip-publish --rm-dist
    when:
      event:
        - tag
      status:
        - success
volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock